import * as images from "./img/index.js";

export const stepsSlider = {
    block12: [
        {
            id: 121,
            text: 'Откройте мобильное приложение и нажмите «Войти»',
            idCatalog: 'block12&otkroite_mp',
            imageMobile: null,
            imageTablet: images.phoneImg121,
        },
        {
            id: 122,
            text: 'Выберите вход по номеру карты или логину',
            idCatalog: 'block12&vibirite_vhod',
            imageMobile: images.phoneImg122M,
            imageTablet: images.phoneImg122,
        },
        {
            id: 123,
            text: 'Логин – это идентификатор, который вы получили в офисе при оформлении или который установили самостоятельно',
            idCatalog: 'block12&login',
            imageMobile: images.phoneImg123M,
            imageTablet: images.phoneImg123,
        },
        {
            id: 124,
            text: 'Создайте короткий пароль, Touch ID или Face ID для последующих входов',
            idCatalog: 'block12&sozdaite_parol',
            imageMobile: null,
            imageTablet: images.phoneImg124,
        }
    ],
    block13: [
        {
            id: 131,
            text: 'На платформе IOS в настройках телефона «App Store» переведите в активное положение ползунок «Приложения»',
            idCatalog: 'block13&avtoobnovlenie_ios',
            imageMobile: images.phoneImg1S,
            imageTablet: images.phoneImg1,
        },
        {
            id: 132,
            text: 'На Android зайдите в настройки Play Маркета в раздел «Автообновление приложений» и выберите предпочтительный способ обновления',
            idCatalog: 'block13&avtoobnovlenie_android',
            imageMobile: images.phoneImg2S,
            imageTablet: images.phoneImg2,
        },
        {
            id: 133,
            text: 'Для самостоятельного обновления приложения на IOS и Android в маркетплейсе введите в поиске «УБРиР» и нажмите «Обновить»',
            idCatalog: 'block13&samostoyatelnoe_obnovlenie',
            imageMobile: images.phoneImg3S,
            imageTablet: images.phoneImg3,
        },
    ],
    block14: [
        {
            id: 141,
            text: 'Восстановить доступ можно по номеру карты',
            idCatalog: 'block14&vosstanovit_dostup',
            imageMobile: images.phoneImg131M,
            imageTablet: images.phoneImg131,
        },
        {
            id: 142,
            text: 'Отсканируйте карту или введите ее данные вручную',
            idCatalog: 'block14&dannie_karti',
            imageMobile: images.phoneImg132M,
            imageTablet: images.phoneImg132,
        },
        {
            id: 143,
            text: 'Введите проверочный код, отправленный на номер, привязанный к интернет-банку. Придумайте пароль и введите проверочный код для его подтверждения. Готово!',
            idCatalog: 'block14&vvedite_cod',
            imageMobile: null,
            imageTablet: images.phoneImg133,
        },
    ],
    block21: [
        {
            id: 211,
            text: 'Выберите счет, который хотите пополнить, и нажмите «Пополнить»',
            idCatalog: 'block21&vibirite_schet',
            imageMobile: null,
            imageTablet: images.phoneImg211,
        },
        {
            id: 212,
            text: 'Выберите способ пополнения',
            idCatalog: 'block21&vibirite_sposob',
            imageMobile: images.phoneImg212M,
            imageTablet: images.phoneImg212,
        },
        {
            id: 213,
            text: 'Пополните счет со своего счета или с карты другого банка, предварительно добавив ее',
            idCatalog: 'block21&popolnite_schet',
            imageMobile: null,
            imageTablet: images.phoneImg213,
        },
        {
            id: 214,
            text: 'Или запросите платеж — скопируйте ссылку или поделитесь ей в мессенджерах. Платеж от отправителя поступит вам мгновенно и без комиссий',
            idCatalog: 'block21&zaprosite_platezh',
            imageMobile: images.phoneImg214M,
            imageTablet: images.phoneImg214,
        },
        {
            id: 215,
            text: 'Для пополнения своего счета в УБРиР из другого банка через СБП, выберите банк и сумму',
            idCatalog: 'block21&dlya_popolneniya',
            imageMobile: null,
            imageTablet: images.phoneImg215,
        },
    ],
    block22: [
        {
            id: 221,
            text: 'Нажмите «Все мои продукты» и выберите основной счет. Он будет предлагаться первым для переводов и платежей',
            idCatalog: 'block22&vibirite_schet',
            imageMobile: images.phoneImg221M,
            imageTablet: images.phoneImg221,
        },
        {
            id: 222,
            text: 'В сплывающем меню выберите «Сделать основным»',
            idCatalog: 'block22&sdelat_osnovnim',
            imageMobile: images.phoneImg221M,
            imageTablet: images.phoneImg221,
        },
        {
            id: 223,
            text: 'Выберите счет, нажмите «Оплатить». Осуществится переход в раздел «Платежи и переводы», где вы можете выбрать интересующую вас оплату',
            idCatalog: 'block22&oplatit_so_scheta',
            imageMobile: images.phoneImg223M,
            imageTablet: images.phoneImg223,
        },
        {
            id: 224,
            text: 'Просматривайте реквизиты счета и делитесь ими',
            idCatalog: 'block22&prosmatrivaite_rekviziti',
            imageMobile: null,
            imageTablet: images.phoneImg224,
        },
        {
            id: 225,
            text: 'Переименовывайте счет',
            idCatalog: 'block22&pereimenovivaite_schet',
            imageMobile: null,
            imageTablet: images.phoneImg225,
        },
    ],
    block23: [
        {
            id: 231,
            text: 'Выберите счет, по которому хотите посмотреть выписку. Последние операции видны в этом же окне',
            idCatalog: 'block23&vibirite_schet',
            imageMobile: images.phoneImg231M,
            imageTablet: images.phoneImg231,
        },
        {
            id: 232,
            text: 'Нажмите «Выписка по счету» или «Открыть историю операций»',
            idCatalog: 'block23&vipiska_po_schetu',
            imageMobile: images.phoneImg232M,
            imageTablet: images.phoneImg233,
        },
        {
            id: 233,
            text: 'Наглядно просматривайте выписку, используйте дополнительные фильтры',
            idCatalog: 'block23&prosmatrivaite_vipisku',
            imageMobile: images.phoneImg233M,
            imageTablet: images.phoneImg233,
        },
        {
            id: 234,
            text: 'Отправляйте выписку на e-mail',
            idCatalog: 'block23&otpravlyaite_vipisku',
            imageMobile: null,
            imageTablet: images.phoneImg234,
        },
        {
            id: 235,
            text: 'Сохраняйте или отправляйте в любой мессенджер прямо из приложения в разделе «Заказанные выписки»',
            idCatalog: 'block23&sokhranyayte_ili_otpravlyaite',
            imageMobile: images.phoneImg236M,
            imageTablet: images.phoneImg236,
        },
        {
            id: 236,
            text: 'Детально просматривайте платежи, повторяйте, сохраняйте квитанции, копируйте данные',
            idCatalog: 'block23&prosmatrivaite_platezhi',
            imageMobile: images.phoneImg235M,
            imageTablet: images.phoneImg235,
        },
    ],
    block24: [
        {
            id: 241,
            text: 'Выберите счет, по которому хотите получить справку, и нажмите «Справка о доступном остатке»',
            idCatalog: 'block24&vibirite_schet',
            imageMobile: images.phoneImg241M,
            imageTablet: images.phoneImg241,
        },
        {
            id: 242,
            text: 'Отправьте справку на e-mail',
            idCatalog: 'block24&otpavte_spravku',
            imageMobile: images.phoneImg242M,
            imageTablet: images.phoneImg242,
        },
    ],
    block31: [
        {
            id: 311,
            text: 'Нажмите оформить кредит в блоке «Оформление продуктов»',
            idCatalog: 'block31&oformit_kredit',
            imageMobile: images.phoneImg311M,
            imageTablet: images.phoneImg311,
        },
        {
            id: 312,
            text: 'Ознакомьтесь с преимуществами кредита и нажмите «Рассчитать»',
            idCatalog: 'block31&oznakomtes_s_preimushestvami',
            imageMobile: images.phoneImg312M,
            imageTablet: images.phoneImg312,
        },
        {
            id: 313,
            text: 'Заполните анкету с персональными данными',
            idCatalog: 'block31&zapolnite_anketu',
            imageMobile: null,
            imageTablet: images.phoneImg313,
        },
        {
            id: 314,
            text: 'Для увеличения суммы кредита подтвердите свой доход, используя подтвержденную учетную запись на Гос.услугах и данные СНИЛС',
            idCatalog: 'block31&podtverdite_dohod',
            imageMobile: images.phoneImg314M,
            imageTablet: images.phoneImg314,
        },
        {
            id: 315,
            text: 'Сформируйте запрос на расчет лимита, ознакомьтесь со списком документов и подтвердите отправку кодом из SMS',
            idCatalog: 'block31&sformiruite_zapros',
            imageMobile: null,
            imageTablet: images.phoneImg315,
        },
        {
            id: 316,
            text: 'Статус заявки появится на главном экране. Ожидайте ответ в течение 5 минут',
            idCatalog: 'block31&status_zayavki',
            imageMobile: images.phoneImg316M,
            imageTablet: images.phoneImg316,
        },
        {
            id: 317,
            text: 'Решение появится на главном экране, продолжите оформление кликом на него',
            idCatalog: 'block31&reshenie',
            imageMobile: images.phoneImg317M,
            imageTablet: images.phoneImg317,
        },
        {
            id: 318,
            text: 'Ознакомьтесь с персональными условиями, выберите желаемую сумму и срок кредита',
            idCatalog: 'block31&vibirite_summu',
            imageMobile: null,
            imageTablet: images.phoneImg318,
        },
        {
            id: 319,
            text: 'Ознакомьтесь с условиями договора и подтвердите согласие',
            idCatalog: 'block31&oznakomtes_s_usloviyami',
            imageMobile: null,
            imageTablet: images.phoneImg319,
        },
        {
            id: 3110,
            text: 'Ожидайте зачисление кредита на карту в течение 5 минут и не забудьте оплатить страховку – она уменьшит ставку до 5%',
            idCatalog: 'block31&ozhidaite_zachislenie',
            imageMobile: images.phoneImg3110M,
            imageTablet: images.phoneImg3110,
        },
        {
            id: 3111,
            text: 'После оформления оплатите страховку',
            idCatalog: 'block31&oplatite_strahovku',
            imageMobile: images.phoneImg3111M,
            imageTablet: images.phoneImg3111,
        },
    ],
    block32: [
        {
            id: 321,
            text: 'После оформления кредит появится на главном экране в блоке «Кредиты»',
            idCatalog: 'block32&posle_oformleniya',
            imageMobile: images.phoneImg321M,
            imageTablet: images.phoneImg321,
        },
        {
            id: 322,
            text: 'Вся информация о сумме и платежах видна в карточке кредита',
            idCatalog: 'block32&inform_v_kartochke',
            imageMobile: null,
            imageTablet: images.phoneImg322,
        },
        {
            id: 323,
            text: 'Вносите платежи любым способом',
            idCatalog: 'block32&vnosite_platezhi',
            imageMobile: images.phoneImg323M,
            imageTablet: images.phoneImg323,
        },
        {
            id: 324,
            text: 'Переводом со своего счета',
            idCatalog: 'block32&perevodom_so_svoego_scheta',
            imageMobile: null,
            imageTablet: images.phoneImg324,
        },
        {
            id: 325,
            text: 'Или переводом с карты другого банка, предварительно добавив ее',
            idCatalog: 'block32&perevodom_iz_dr_banka',
            imageMobile: null,
            imageTablet: images.phoneImg325,
        },
        {
            id: 326,
            text: 'Вносите платежи по кредиту досрочно – график платежей просчитается на следующий день',
            idCatalog: 'block32&vnosite_dosrochno',
            imageMobile: images.phoneImg326M,
            imageTablet: images.phoneImg326,
        },
        {
            id: 327,
            text: 'Быстрый доступ к истории платежей за текущий месяц',
            idCatalog: 'block32&bistrii_dostup',
            imageMobile: null,
            imageTablet: images.phoneImg327,
        },
        {
            id: 328,
            text: 'Следите за графиком платежей',
            idCatalog: 'block32&sledite_za_grafikom',
            imageMobile: null,
            imageTablet: images.phoneImg328,
        },
        {
            id: 329,
            text: 'Смотрите реквизиты счета кредита и делитесь ими',
            idCatalog: 'block32&smotrite_rekviziti',
            imageMobile: null,
            imageTablet: images.phoneImg329,
        },
        {
            id: 3210,
            text: 'На странице кредита выберите «Договор по действующему кредиту». Просмотрите договор',
            idCatalog: 'block32&dogovor_po_kreditu',
            imageMobile: images.phoneImg3210M,
            imageTablet: images.phoneImg3210,
        },
        {
            id: 3211,
            text: 'При необходимости нажмите «Сохранить или переслать». Выберите удобный способ через мессенжеры, либо отправить на e-mail',
            idCatalog: 'block32&sohranit_ili_pereslat',
            imageMobile: images.phoneImg3211M,
            imageTablet: images.phoneImg3211,
        },
        {
            id: 3212,
            text: 'Оформляйте справку о погашении задолженности физического лица и справку об уплаченных процентах по кредиту в разделе «Еще» → «Выписки и справки»',
            idCatalog: 'block32&spravka_o_pagashenii',
            imageMobile: images.phoneImg3212M,
            imageTablet: images.phoneImg3212,
        },
    ],
    block41: [
        {
            id: 411,
            text: 'Нажмите «Оформить кредитную карту» в блоке «Оформление продуктов»',
            idCatalog: 'block41&oformit_kk',
            imageMobile: images.phoneImg411M,
            imageTablet: images.phoneImg411,
        },
        {
            id: 412,
            text: 'Ознакомьтесь с преимуществами карты и нажмите «Оформить карту»',
            idCatalog: 'block41&oznakomtes_s_preimushestvami_kk',
            imageMobile: images.phoneImg412M,
            imageTablet: images.phoneImg412,
        },
        {
            id: 413,
            text: 'Заполните анкету с персональными данными',
            idCatalog: 'block41&zapolnite_anketu_kk',
            imageMobile: null,
            imageTablet: images.phoneImg413,
        },
        {
            id: 414,
            text: 'Сформируйте запрос на расчет лимита, ознакомьтесь со списком документов и подтвердите отправку кодом из SMS',
            idCatalog: 'block41&sformiruite_zapros_kk',
            imageMobile: null,
            imageTablet: images.phoneImg414,
        },
        {
            id: 415,
            text: 'Статус заявки появится на главном экране. Ожидайте ответ в течение 5 минут',
            idCatalog: 'block41&status_zayavki_kk',
            imageMobile: images.phoneImg415M,
            imageTablet: images.phoneImg415,
        },
        {
            id: 416,
            text: 'Решение появится на главном экране, продолжите оформление кликом на него',
            idCatalog: 'block41&reshenie_kk',
            imageMobile: images.phoneImg416M,
            imageTablet: images.phoneImg416,
        },
        {
            id: 417,
            text: 'Ознакомьтесь с персональными условиями, выберите карту и желаемый лимит',
            idCatalog: 'block41&vibirite_limit_kk',
            imageMobile: images.phoneImg417M,
            imageTablet: images.phoneImg417,
        },
        {
            id: 418,
            text: 'Ознакомьтесь с условиями договора и подтвердите согласие',
            idCatalog: 'block41&oznakomtes_s_usloviyami_kk8',
            imageMobile: null,
            imageTablet: images.phoneImg418,
        },
        {
            id: 419,
            text: 'Ожидайте итоговое решение в течение 5 минут. Если вы выбрали тип карты «Пластиковая» – мы свяжемся с вами и договоримся о доставке',
            idCatalog: 'block41&ozidaite_itogovoe_reshenie_kk',
            imageMobile: images.phoneImg419M,
            imageTablet: images.phoneImg419,
        },
    ],
    block42: [
        {
            id: 421,
            text: 'После оформления кредитная карта появится в блоке «Счета и вклады» с названием «Счет кредитной карты»',
            idCatalog: 'block42&posle_oformleniya_kk',
            imageMobile: images.phoneImg421M,
            imageTablet: images.phoneImg421,
        },
        {
            id: 422,
            text: 'Ознакомьтесь с подробной информацией по льготному периоду, сумме и сроку минимального платежа',
            idCatalog: 'block42&oznakomtes_podrobno',
            imageMobile: images.phoneImg422M,
            imageTablet: images.phoneImg422,
        },
        {
            id: 423,
            text: 'Вносите платежи любым способом',
            idCatalog: 'block42&vnosite_platezhi_kk',
            imageMobile: images.phoneImg423M,
            imageTablet: images.phoneImg423,
        },
        {
            id: 424,
            text: 'Просматривайте детали кредитной карты',
            idCatalog: 'block42&prosmatrivaite_detali',
            imageMobile: images.phoneImg424M,
            imageTablet: images.phoneImg424,
        },
        {
            id: 425,
            text: 'Отслеживайте информацию по выплаченному и начисленному кэшбэку',
            idCatalog: 'block42&otslezhivaite_kb',
            imageMobile: images.phoneImg425M,
            imageTablet: images.phoneImg425,
        },
    ],
    block43: [
        {
            id: 431,
            text: 'На главном экране нажмите «Доступно персональное предложение» и «Подробнее» чтобы ознакомиться с ним',
            idCatalog: 'block43&dostupno_predlozhenie',
            imageMobile: images.phoneImg431M,
            imageTablet: images.phoneImg431,
        },
        {
            id: 432,
            text: 'В случае если вы хотите отказаться нажмите на крестик и подтвердите действие',
            idCatalog: 'block43&otkazatsya',
            imageMobile: images.phoneImg432M,
            imageTablet: images.phoneImg432,
        },
        {
            id: 433,
            text: 'Для того чтобы принять предложение ознакомьтесь с офертой и подтвердите операцию смс кодом. Готово!',
            idCatalog: 'block43&prinyat',
            imageMobile: images.phoneImg433M,
            imageTablet: images.phoneImg433,
        },
    ],
    block44: [
        {
            id: 441,
            text: 'На странице Кредитной карты нажмите «Закрыть карту»',
            idCatalog: 'block44&zakrit_kartu',
            imageMobile: images.phoneImg441M,
            imageTablet: images.phoneImg441,
        },
        {
            id: 442,
            text: 'Подтвердите действие SMS-кодом',
            idCatalog: 'block44&podtverdite_sms',
            imageMobile: images.phoneImg442M,
            imageTablet: images.phoneImg442,
        },
        {
            id: 443,
            text: 'Готово! Кредитная карта будет закрыта на следующий день',
            idCatalog: 'block44&done_kk',
            imageMobile: images.phoneImg443M,
            imageTablet: images.phoneImg443,
        },
    ],
    block51: [
        {
            id: 511,
            text: 'Нажмите оформить дебетовую карту в блоке «Оформление продуктов», выберите карту и нажмите «Оформить карту»',
            idCatalog: 'block51&oformit_dk',
            imageMobile: images.phoneImg511M,
            imageTablet: images.phoneImg511,
        },
        {
            id: 512,
            text: 'Укажите счет и номер мобильного телефона для выпуска карты',
            idCatalog: 'block51&ukazhite_schet',
            imageMobile: images.phoneImg512M,
            imageTablet: images.phoneImg512,
        },
        {
            id: 513,
            text: 'Выберите возможность сделать карту виртуальной для моментальной оплаты с помощью смартфона',
            idCatalog: 'block51&sdelat_virtualnoi',
            imageMobile: images.phoneImg513M,
            imageTablet: images.phoneImg513,
        },
        {
            id: 514,
            text: 'Или выберите город и офис для получения дебетовой карты. Готово! Мы свяжемся с вами, когда карта будет готова',
            idCatalog: 'block51&ili_vibirite_gorod',
            imageMobile: images.phoneImg514M,
            imageTablet: images.phoneImg514,
        },
    ],
    block52: [
        {
            id: 521,
            text: 'После оформления карты выберете ее на странице счета и нажмите «Активировать пластиковую карту»',
            idCatalog: 'block52&aktivirovat_kartu',
            imageMobile: images.phoneImg521M,
            imageTablet: images.phoneImg521,
        },
        {
            id: 522,
            text: 'Введите пропущенные цифры номера карты',
            idCatalog: 'block52&vvedite_cifri',
            imageMobile: images.phoneImg522M,
            imageTablet: images.phoneImg522,
        },
        {
            id: 523,
            text: 'Готово! Карта активирована. Установите ПИН-код для карты',
            idCatalog: 'block52&done',
            imageMobile: images.phoneImg523M,
            imageTablet: images.phoneImg523,
        },
    ],
    block53: [
        {
            id: 531,
            text: 'После оформления карты нажмите на кнопку «Показать номер карты и CVC/CVV». Просматривайте и копируйте данные для покупок или переводов',
            idCatalog: 'block53&dannie_po_karte',
            imageMobile: images.phoneImg531M,
            imageTablet: images.phoneImg531,
        },
        {
            id: 532,
            text: 'Просматривайте реквизиты и копируйте любые поля на странице счета',
            idCatalog: 'block53&copiruite_rekviziti',
            imageMobile: images.phoneImg532M,
            imageTablet: images.phoneImg532,
        },
        {
            id: 533,
            text: 'Зайдите на страницу счета и выберите карту, по которой хотите совершить настройки или посмотреть информацию',
            idCatalog: 'block53&vibirite_kartu',
            imageMobile: images.phoneImg533M,
            imageTablet: images.phoneImg533,
        },
        {
            id: 534,
            text: 'На странице карты ознакомьтесь со всеми функциями, которые можно использовать',
            idCatalog: 'block53&oznakomtes_s_funkziyami',
            imageMobile: null,
            imageTablet: images.phoneImg534,
        },
        {
            id: 535,
            text: 'Быстрый доступ к последним операциям',
            idCatalog: 'block53&bistrii_dostup',
            imageMobile: null,
            imageTablet: images.phoneImg535,
        },
        {
            id: 536,
            text: 'Подробнее ознакомьтесь с тарифным планом',
            idCatalog: 'block53&oznakomtes_s_tp',
            imageMobile: null,
            imageTablet: images.phoneImg536,
        },
    ],
    block56: [
        {
            id: 561,
            text: 'Зайдите на страницу счета и выберите карту, по которой хотите настроить лимиты',
            idCatalog: 'block56&vibirite_kartu_lim',
            imageMobile: images.phoneImg561M,
            imageTablet: images.phoneImg561,
        },
        {
            id: 562,
            text: 'Выберите операции, на которые хотите настроить лимит',
            idCatalog: 'block56&vibirite_operacii_lim',
            imageMobile: images.phoneImg562M,
            imageTablet: images.phoneImg562,
        },
        {
            id: 563,
            text: 'Установите лимит и подтвердите действие',
            idCatalog: 'block56&ustanovite_limit',
            imageMobile: null,
            imageTablet: images.phoneImg563,
        },
        {
            id: 564,
            text: 'В разделе лимиты будут видны все настройки',
            idCatalog: 'block56&vse_nastroiki',
            imageMobile: null,
            imageTablet: images.phoneImg564,
        },
    ],
    block57: [
        {
            id: 571,
            text: 'Зайдите на страницу счета и выберите карту, по которой хотите изменить ПИН-код',
            idCatalog: 'block57&vibirite_kartu_pin',
            imageMobile: images.phoneImg571M,
            imageTablet: images.phoneImg571,
        },
        {
            id: 572,
            text: 'Придумайте ПИН-код',
            idCatalog: 'block57&pridumaite_pin',
            imageMobile: null,
            imageTablet: images.phoneImg572,
        },
        {
            id: 573,
            text: 'Подтвердите ПИН-код SMS-кодом',
            idCatalog: 'block57&podtverdite_pin',
            imageMobile: null,
            imageTablet: images.phoneImg573,
        },
        {
            id: 574,
            text: 'Готово! ПИН-код изменен',
            idCatalog: 'block57&done_pin',
            imageMobile: null,
            imageTablet: images.phoneImg574,
        },
    ],
    block58: [
        {
            id: 581,
            text: 'Зайдите на страницу счета и выберите карту, по которой желаете настроить уведомления',
            idCatalog: 'block58&vibirite_kartu_uvedomleniya',
            imageMobile: images.phoneImg581M,
            imageTablet: images.phoneImg581,
        },
        {
            id: 582,
            text: 'Настройте уведомления  удобным для вас способом: бесплатные пуши, e-mail и телефон',
            idCatalog: 'block58&podkluchit_uvedomleniya',
            imageMobile: images.phoneImg582M,
            imageTablet: images.phoneImg582,
        },
        {
            id: 583,
            text: 'Управляйте уведомлениями – добавляйте и удаляйте',
            idCatalog: 'block58&upravlyaite_uvedomleniya',
            imageMobile: images.phoneImg583M,
            imageTablet: images.phoneImg583,
        },
    ],
    block59: [
        {
            id: 591,
            text: 'После оформления карта появится в вашем мобильном приложении. Зайдите на страницу счета и выберите ее',
            idCatalog: 'block59&karta_v_mp_kb',
            imageMobile: images.phoneImg591M,
            imageTablet: images.phoneImg591,
        },
        {
            id: 592,
            text: 'На странице карты виден ваш кэшбэк и рубрика повышенного кэшбэка',
            idCatalog: 'block59&kb_i_rubrika',
            imageMobile: images.phoneImg592M,
            imageTablet: images.phoneImg592,
        },
        {
            id: 593,
            text: 'Управляйте рубриками хоть каждый месяц! Выбирайте рубрику для повышенного кэшбэка из 16 представленных',
            idCatalog: 'block59&upravlyaite_rubrikami_kb',
            imageMobile: null,
            imageTablet: images.phoneImg593,
        },
        {
            id: 594,
            text: 'Переводите баллы в рубли',
            idCatalog: 'block59&proveryaite_balli',
            imageMobile: null,
            imageTablet: images.phoneImg594,
        },
        {
            id: 595,
            text: 'Получайте уведомления по всем изменениям',
            idCatalog: 'block59&poluchaite_uvedomleniya',
            imageMobile: null,
            imageTablet: images.phoneImg595,
        },
    ],
    block510: [
        {
            id: 5101,
            text: 'Зайдите на страницу счета и выберите карту, которую хотите заблокировать',
            idCatalog: 'block510&vibirite_kartu_blocking',
            imageMobile: images.phoneImg5101M,
            imageTablet: images.phoneImg5101,
        },
        {
            id: 5102,
            text: 'Выберите причину блокировки карты',
            idCatalog: 'block510&vibirite_prichinu_blocking',
            imageMobile: images.phoneImg5102M,
            imageTablet: images.phoneImg5102,
        },
        {
            id: 5103,
            text: 'Подтвердите действие',
            idCatalog: 'block510&podtverdite_deistvie_blocking',
            imageMobile: images.phoneImg5103M,
            imageTablet: images.phoneImg5103,
        },
        {
            id: 5104,
            text: 'Готово! Карта заблокирована',
            idCatalog: 'block510&done_blocking',
            imageMobile: images.phoneImg5104M,
            imageTablet: images.phoneImg5104,
        },
        {
            id: 5105,
            text: 'Если вы указали «Временная блокировка», карту можно разблокировать',
            idCatalog: 'block510&vremennaya_blocking',
            imageMobile: images.phoneImg5105M,
            imageTablet: images.phoneImg5105,
        },
    ],
    block511: [
        {
            id: 511,
            text: 'Зайдите на страницу счета и выберите карту, которую хотите закрыть',
            idCatalog: 'block511&vibirite_kartu_zakrit',
            imageMobile: images.phoneImg5111M,
            imageTablet: images.phoneImg5111,
        },
        {
            id: 512,
            text: 'Подтвердите согласие на закрытие карты',
            idCatalog: 'block511&podtverdite_soglasie_zakrit',
            imageMobile: images.phoneImg5112M,
            imageTablet: images.phoneImg5112,
        },
        {
            id: 513,
            text: 'Готово! Карта будет закрыта на следующий день',
            idCatalog: 'block511&done_zakrit',
            imageMobile: images.phoneImg5113M,
            imageTablet: images.phoneImg5113,
        },
    ],
    block61: [
        {
            id: 611,
            text: 'Нажмите «Открыть вклад или счет» в блоке «Оформление продуктов» и ознакомьтесь с условиями вклада',
            idCatalog: 'block61&oformit_vklad',
            imageMobile: images.phoneImg611M,
            imageTablet: images.phoneImg611,
        },
        {
            id: 612,
            text: 'Укажите счет, с которого хотите открыть вклад и нажмите «Открыть»',
            idCatalog: 'block61&ukazhite_schet2',
            imageMobile: null,
            imageTablet: images.phoneImg612,
        },
        {
            id: 613,
            text: 'Вклад появится в разделе «Сбережения». Просматривайте, сохраняйте или пересылайте договор по вкладу',
            idCatalog: 'block61&done_vklad',
            imageMobile: images.phoneImg613M,
            imageTablet: images.phoneImg613,
        },
        {
            id: 614,
            text: 'Смотрите график выплаты процентов',
            idCatalog: 'block61&smotrite_grafik',
            imageMobile: null,
            imageTablet: images.phoneImg614,
        },
    ],
    block63: [
        {
            id: 631,
            text: 'При открытии «Накопительного счёта» или онлайн-вклада выберите «Приумножить накопления»',
            idCatalog: 'block63&priumnozhit_nakopleniya',
            imageMobile: images.phoneImg631M,
            imageTablet: images.phoneImg631,
        },
        {
            id: 632,
            text: 'Укажите счёт, с которого хотите открыть «Накопительный счёт» или онлайн-вклад',
            idCatalog: 'block63&ukazhite_schet_ns',
            imageMobile: null,
            imageTablet: images.phoneImg632,
        },
        {
            id: 633,
            text: 'Подтвердите согласие на оплату опции',
            idCatalog: 'block63&podtverdite_soglasie_ns',
            imageMobile: images.phoneImg633M,
            imageTablet: images.phoneImg633,
        },
        {
            id: 634,
            text: 'Статус опции будет виден на странице «Накопительного счёта»/онлайн-вклада',
            idCatalog: 'block63&status_na_stranice_ns',
            imageMobile: images.phoneImg634M,
            imageTablet: images.phoneImg634,
        },
        {
            id: 635,
            text: 'Вы сможете в любой момент отключить опцию на странице с информацией об онлайн-вкладе или «Накопительном счёте»',
            idCatalog: 'block63&otkluchit_opciu_ns',
            imageMobile: images.phoneImg635M,
            imageTablet: images.phoneImg635,
        },
    ],
    block64: [
        {
            id: 641,
            text: 'Откройте главный экран приложения УБРиР и выберите вклад, который необходимо пополнить',
            idCatalog: 'block64&vibirite_vklad_popolnenie',
            imageMobile: null,
            imageTablet: images.phoneImg641,
        },
        {
            id: 642,
            text: 'Нажмите «Пополнить»',
            idCatalog: 'block64&poplnit_vklad',
            imageMobile: null,
            imageTablet: images.phoneImg642,
        },
        {
            id: 643,
            text: 'Выберите счет, с которого хотите пополнить вклад, и укажите необходимую сумму. Средства поступят на счет мгновенно',
            idCatalog: 'block64&vibirite_schet_vklada_popolnenie',
            imageMobile: images.phoneImg643M,
            imageTablet: images.phoneImg643,
        },
    ],
    block65: [
        {
            id: 651,
            text: 'Откройте главный экран приложения УБРиР и выберите вклад, с которого необходимо снять средства',
            idCatalog: 'block65&vibirite_vklad_snyatie',
            imageMobile: null,
            imageTablet: images.phoneImg651,
        },
        {
            id: 652,
            text: 'Нажмите «Снять»',
            idCatalog: 'block65&snyat',
            imageMobile: null,
            imageTablet: images.phoneImg652,
        },
        {
            id: 653,
            text: 'Выберите частичное или полное снятие',
            idCatalog: 'block65&chastichnoe_ili_polnoe',
            imageMobile: images.phoneImg653M,
            imageTablet: images.phoneImg653,
        },
        {
            id: 654,
            text: 'Выберите счет, на который хотите перевести деньги со вклада, и укажите необходимую сумму. Средства поступят на счет мгновенно',
            idCatalog: 'block65&vibirite_schet_snyatie',
            imageMobile: null,
            imageTablet: images.phoneImg654,
        },
    ],
    block66: [
        {
            id: 661,
            text: 'Откройте главный экран и нажмите "Все мои продукты"',
            idCatalog: 'block66&pokazat_vse',
            imageMobile: null,
            imageTablet: images.phoneImg661,
        },
        {
            id: 662,
            text: 'Из перечня своих счетов и вкладов выберите «Вклад до востребования»',
            idCatalog: 'block66&vklad_do_vostrebovaniya',
            imageMobile: null,
            imageTablet: images.phoneImg662,
        },
        {
            id: 663,
            text: 'Затем в карточке вклада нажмите «Снять» и выберите счет для перечисления',
            idCatalog: 'block66&snyat',
            imageMobile: null,
            imageTablet: images.phoneImg663,
        },
        {
            id: 664,
            text: 'Укажите сумму и еще раз проверьте выбранные данные, нажмите «Подтвердить»',
            idCatalog: 'block66&podtverdit',
            imageMobile: images.phoneImg664M,
            imageTablet: images.phoneImg664,
        },
        {
            id: 665,
            text: 'Готово! Средства поступят на выбранный счет в течение дня',
            idCatalog: 'block66&done_do_vostrebovaniya',
            imageMobile: images.phoneImg665M,
            imageTablet: images.phoneImg665,
        },
    ],
    block67: [
        {
            id: 671,
            text: 'Нажмите на «Закрыть счет» из продуктовой карточки на главной странице приложения или на странице накопительного счета',
            idCatalog: 'block67&zakrit_schet',
            imageMobile: images.phoneImg671M,
            imageTablet: images.phoneImg671,
        },
        {
            id: 672,
            text: 'Выберите счет для перевода средств',
            idCatalog: 'block67&vibirite_schet',
            imageMobile: null,
            imageTablet: images.phoneImg672,
        },
        {
            id: 673,
            text: 'На следующий день счет будет закрыт, и денежные средства поступят на выбранный счет',
            idCatalog: 'block67&schet_zakrit',
            imageMobile: images.phoneImg673M,
            imageTablet: images.phoneImg673,
        },
    ],
    block68: [
        {
            id: 681,
            text: 'Подпишите согласие SMS-кодом',
            idCatalog: 'block68&podpishite_soglasie',
            imageMobile: null,
            imageTablet: images.phoneImg681,
        },
        {
            id: 682,
            text: 'После подписания документов перейдите к оплате',
            idCatalog: 'block68&oplata',
            imageMobile: null,
            imageTablet: images.phoneImg682,
        },
        {
            id: 683,
            text: 'Переведите деньги по реквизитам',
            idCatalog: 'block68&perevedite_ds',
            imageMobile: images.phoneImg683M,
            imageTablet: images.phoneImg683,
        },
        {
            id: 684,
            text: 'Укажите сумму и еще раз проверьте выбранные данные, нажмите «Подтвердить»',
            idCatalog: 'block68&podtverdit',
            imageMobile: null,
            imageTablet: images.phoneImg684,
        },
    ],
    block71: [
        {
            id: 711,
            text: 'Перейдите в «Платежи и переводы». Пользуйтесь популярными операциями или перейдите в «Показать все»',
            idCatalog: 'block71&platezhi_i_perevodi',
            imageMobile: images.phoneImg711M,
            imageTablet: images.phoneImg711,
        },
        {
            id: 712,
            text: 'Выберите необходимый тип платежа или услугу',
            idCatalog: 'block71&vibirite_tip_uslugu',
            imageMobile: images.phoneImg712M,
            imageTablet: images.phoneImg712,
        },
        {
            id: 713,
            text: 'Или воспользуйтесь поиском по вендору',
            idCatalog: 'block71&poisk',
            imageMobile: images.phoneImg713M,
            imageTablet: images.phoneImg713,
        },
        {
            id: 714,
            text: 'Совершайте переводы по номеру карты, используя ручной ввод или опцию сканирования',
            idCatalog: 'block71&oplata_po_nomeru_karti',
            imageMobile: images.phoneImg714M,
            imageTablet: images.phoneImg714,
        },
        {
            id: 715,
            text: 'После совершения платежа или перевода добавьте его в шаблон для дальнейшего использования',
            idCatalog: 'block71&shablon',
            imageMobile: images.phoneImg715M,
            imageTablet: images.phoneImg715,
        },
    ],
    block72: [
        {
            id: 721,
            text: 'Подключите СБП в меню «Еще»: укажите номер телефона и счет для переводов из других банков',
            idCatalog: 'block72&podkluchenie',
            imageMobile: images.phoneImg721M,
            imageTablet: images.phoneImg721,
        },
        {
            id: 722,
            text: 'Перейдите в «Платежи и переводы» и выберите «СБП» и тип перевода: по номеру телефона или из другого банка через СБП',
            idCatalog: 'block72&sbp',
            imageMobile: images.phoneImg722M,
            imageTablet: images.phoneImg722,
        },
        {
            id: 723,
            text: 'Выберите банк получателя и укажите сумму перевода, нажмите «Перевести». Готово! Для того чтобы каждый раз не приходилось делать переводы СБП заново, добавьте их в быстрые шаблоны по кнопке «В избранное» или нажмите «Повторить» в деталях операции» в блоке',
            idCatalog: 'block72&done_sbp',
            imageMobile: images.phoneImg723M,
            imageTablet: images.phoneImg723,
        },
        {
            id: 724,
            text: 'Для оплаты покупки через СБП отсканируйте QR-код или перейдите по платежной ссылке на сайте магазина, затем подтвердите оплату в приложении банка',
            idCatalog: 'block72&oplata_sbp',
            imageMobile: images.phoneImg724M,
            imageTablet: images.phoneImg724,
        },
    ],
    block73: [
        {
            id: 731,
            text: 'Перейдите в «Платежи» и выберите «Оплата по QR-коду»',
            idCatalog: 'block73&oplata_po_QR',
            imageMobile: images.phoneImg731M,
            imageTablet: images.phoneImg731,
        },
        {
            id: 732,
            text: 'Наведите на QR-код в квитанции или загрузите квитанцию из фотогалереи',
            idCatalog: 'block73&navedite_na_QR',
            imageMobile: images.phoneImg732M,
            imageTablet: images.phoneImg732,
        },
        {
            id: 733,
            text: 'Все реквизиты заполнятся автоматически, остается только подтвердить. Готово!',
            idCatalog: 'block73&done_QR',
            imageMobile: images.phoneImg733M,
            imageTablet: images.phoneImg733,
        },
    ],
    block74: [
        {
            id: 741,
            text: 'Перейдите в «Платежи» и выберите «Показать все»',
            idCatalog: 'block74&platezhi_pokazat_vse',
            imageMobile: images.phoneImg741M,
            imageTablet: images.phoneImg741,
        },
        {
            id: 742,
            text: 'Легко оплачивайте мобильную связь и интернет',
            idCatalog: 'block74&mob_svyaz_internet',
            imageMobile: images.phoneImg742M,
            imageTablet: images.phoneImg742,
        },
        {
            id: 743,
            text: 'А также коммунальные платежи и ЖКХ',
            idCatalog: 'block74&kommunalnie_platezhi',
            imageMobile: images.phoneImg743M,
            imageTablet: images.phoneImg743,
        },
        {
            id: 744,
            text: 'Оплачивайте штрафы ГИБДД',
            idCatalog: 'block74&shtrafi_gbdd',
            imageMobile: images.phoneImg744M,
            imageTablet: images.phoneImg744,
        },
        {
            id: 745,
            text: 'Погашайте кредиты сторонних банков и микрозаймы',
            idCatalog: 'block74&krediti_storonnih_bankov',
            imageMobile: images.phoneImg745M,
            imageTablet: images.phoneImg745,
        },
        {
            id: 746,
            text: 'Оплачивайте детский сад и обучение',
            idCatalog: 'block74&obuchenie',
            imageMobile: null,
            imageTablet: images.phoneImg746,
        },
        {
            id: 747,
            text: 'Оплачивайте через электронные кошельки',
            idCatalog: 'block74&elektronnie_koshelki',
            imageMobile: null,
            imageTablet: images.phoneImg747,
        },
    ],
    block75: [
        {
            id: 751,
            text: 'Создайте автоплатеж из истории платежей или сразу после того, как совершили его',
            idCatalog: 'block75&avtoplatezh',
            imageMobile: images.phoneImg751M,
            imageTablet: images.phoneImg751,
        },
        {
            id: 752,
            text: 'Укажите периодичность и выберите дату',
            idCatalog: 'block75&periodichnost_i_data',
            imageMobile: images.phoneImg752M,
            imageTablet: images.phoneImg752,
        },
        {
            id: 753,
            text: 'Выберите счет, с которого будет происходить списание, и укажите необходимую сумму',
            idCatalog: 'block75&vibirite_schet_avtoplatezhi',
            imageMobile: images.phoneImg753M,
            imageTablet: images.phoneImg753,
        },
        {
            id: 754,
            text: 'Подтвердите действие SMS-кодом или push-уведомлением',
            idCatalog: 'block75&podtverdite_sms_avtoplatezhi',
            imageMobile: images.phoneImg754M,
            imageTablet: images.phoneImg754,
        },
        {
            id: 755,
            text: 'Готово! Автоплатеж подключен и зафиксирован в блоке «Автоплатежи»',
            idCatalog: 'block75&done_avtoplatezhi',
            imageMobile: null,
            imageTablet: images.phoneImg755,
        },
        {
            id: 756,
            text: 'При необходимости автоплатеж можно редактировать, приостановить, возобновить и удалить',
            idCatalog: 'block75&otkluchit_avtoplatezh',
            imageMobile: images.phoneImg757M,
            imageTablet: images.phoneImg757,
        },
    ],
    block81: [
        {
            id: 811,
            text: 'Перейдите в «Еще» в нижнем меню',
            idCatalog: 'block81&uvedomleniya',
            imageMobile: images.phoneImg811M,
            imageTablet: images.phoneImg811,
        },
        {
            id: 812,
            text: 'Меняйте пароль для входа в мобильное приложение',
            idCatalog: 'block81&menyaite_parol',
            imageMobile: null,
            imageTablet: images.phoneImg812,
        },
        {
            id: 813,
            text: 'Управляйте каналами для получения уведомлений',
            idCatalog: 'block81&upravlyaite_kanalami',
            imageMobile: images.phoneImg813M,
            imageTablet: images.phoneImg813,
        },
    ],
    block82: [
        {
            id: 821,
            text: 'Обращайтесь в чат по любым вопросам. Мы на связи 24/7',
            idCatalog: 'block82&chat',
            imageMobile: images.phoneImg821M,
            imageTablet: images.phoneImg821,
        },
        {
            id: 822,
            text: 'Бесплатно звоните в банк прямо из приложения!',
            idCatalog: 'block82&zvonite_iz_prilozheniya',
            imageMobile: images.phoneImg822M,
            imageTablet: images.phoneImg822,
        },
        {
            id: 823,
            text: 'Эта информация также есть в авторизованной зоне в меню «Еще»',
            idCatalog: 'block82&info',
            imageMobile: images.phoneImg823M,
            imageTablet: images.phoneImg823,
        },
    ],
    block83: [
        {
            id: 831,
            text: 'Переведите в активное положение ползунок «Push-уведомления» в меню «Еще»',
            idCatalog: 'block83&push',
            imageMobile: images.phoneImg831M,
            imageTablet: images.phoneImg831,
        },
        {
            id: 832,
            text: 'Получайте все сообщения от банка через приложение, не занимая место на телефоне sms-сообщениями',
            idCatalog: 'block83&soobsheniya_v_mp',
            imageMobile: images.phoneImg832M,
            imageTablet: images.phoneImg832,
        },
        {
            id: 833,
            text: 'Уведомления будут видны в «колокольчике»',
            idCatalog: 'block83&kolokolchik',
            imageMobile: null,
            imageTablet: images.phoneImg833,
        },
        {
            id: 834,
            text: 'Уведомления разделены по типам: операции по картам, предложения банка и одноразовые пароли',
            idCatalog: 'block83&tipi_uvedomlenii',
            imageMobile: images.phoneImg834M,
            imageTablet: images.phoneImg834,
        },
        {
            id: 835,
            text: 'На главной странице всегда есть актуальные для вас предложения',
            idCatalog: 'block83&predlozheniya',
            imageMobile: images.phoneImg835M,
            imageTablet: images.phoneImg835,
        },
    ],
    block84: [
        {
            id: 841,
            text: 'Просматривайте офисы и банкоматы рядом, мы определим ваше местоположение по геолокации',
            idCatalog: 'block84&ofisi_i_atm',
            imageMobile: images.phoneImg841M,
            imageTablet: images.phoneImg841,
        },
        {
            id: 842,
            text: 'Также вы сможете перейти на офисы и банкоматы после авторизации из меню «Еще»',
            idCatalog: 'block84&is_menu_eshe',
            imageMobile: images.phoneImg842M,
            imageTablet: images.phoneImg842,
        },
        {
            id: 843,
            text: 'Выберите удобный просмотр: на карте или списком',
            idCatalog: 'block84&na_karte_ili_spiskom',
            imageMobile: images.phoneImg843M,
            imageTablet: images.phoneImg843,
        },
        {
            id: 844,
            text: 'Ищите с помощью фильтра',
            idCatalog: 'block84&filtr',
            imageMobile: null,
            imageTablet: images.phoneImg844,
        },
    ],
    block91: [
        {
            id: 911,
            text: 'Нажмите «Подключить овердрафт» в блоке детальной информации по своему текущему дебетовому счету',
            idCatalog: 'block91&podkluchit_overdraft',
            imageMobile: images.phoneImg911M,
            imageTablet: images.phoneImg911,
        },
        {
            id: 912,
            text: 'Ознакомьтесь с преимуществами овердрафта и нажмите «Подать заявку»',
            idCatalog: 'block91&podat_zayavku',
            imageMobile: null,
            imageTablet: images.phoneImg912,
        },
        {
            id: 913,
            text: 'Заполните анкету с персональными данными',
            idCatalog: 'block91&zapolnite_anketu',
            imageMobile: null,
            imageTablet: images.phoneImg913,
        },
        {
            id: 914,
            text: 'Сформируйте запрос на расчет лимита, ознакомьтесь со списком документов и подтвердите отправку кодом из SMS',
            idCatalog: 'block91&sformiruite_zapros',
            imageMobile: null,
            imageTablet: images.phoneImg914,
        },
        {
            id: 915,
            text: 'Статус заявки появится на главном экране. Ожидайте ответ в течение 5 минут',
            idCatalog: 'block91&ozhidaite_otvet',
            imageMobile: null,
            imageTablet: images.phoneImg915,
        },
        {
            id: 916,
            text: 'Решение появится на главном экране, продолжите оформление кликом на него',
            idCatalog: 'block91&reshenie',
            imageMobile: null,
            imageTablet: images.phoneImg916,
        },
        {
            id: 917,
            text: 'Ознакомьтесь с персональными условиями, с условиями договора и подтвердите согласие',
            idCatalog: 'block91&oznakomtes_s_pu',
            imageMobile: null,
            imageTablet: images.phoneImg917,
        },
        {
            id: 918,
            text: 'Ожидайте зачисление овердрафта',
            idCatalog: 'block91&ozhidaite_zachislenie',
            imageMobile: null,
            imageTablet: images.phoneImg918,
        },
    ],
    block92: [
        {
            id: 921,
            text: 'После оформления овердрафта, он отобразится на главном экране в блоке текущего дебетового счета',
            idCatalog: 'block92&posle_oformleniya',
            imageMobile: null,
            imageTablet: images.phoneImg921,
        },
        {
            id: 922,
            text: 'Ознакомьтесь с подробной информацией по овердрафту, сумме и сроку минимального платежа',
            idCatalog: 'block92&oznakomtes_s_informaciei',
            imageMobile: images.phoneImg922M,
            imageTablet: images.phoneImg922,
        },
        {
            id: 923,
            text: 'Вносите платежи любым способом',
            idCatalog: 'block92&vnosite_platezhi',
            imageMobile: images.phoneImg923M,
            imageTablet: images.phoneImg923,
        },
        {
            id: 924,
            text: 'Просматривайте детали овердрафта',
            idCatalog: 'block92&prosmatrivaite_detali',
            imageMobile: null,
            imageTablet: images.phoneImg924,
        },
    ],
    block93: [
        {
            id: 931,
            text: 'На странице «Детали овердрафта» нажмите «Отключить овердрафт»',
            idCatalog: 'block93&otkluchit_overdraft',
            imageMobile: null,
            imageTablet: images.phoneImg931,
        },
        {
            id: 932,
            text: 'Подтвердите действие SMS-кодом',
            idCatalog: 'block93&podtverdite_sms',
            imageMobile: null,
            imageTablet: images.phoneImg932,
        },
        {
            id: 933,
            text: 'Готово! Овердрафт будет закрыт на следующий день',
            idCatalog: 'block93&done',
            imageMobile: null,
            imageTablet: images.phoneImg933,
        },
    ],
    block101: [
        {
            id: 1011,
            text: 'Перейдите в настройки нажав на кнопку «Ещё» и выберите пункт «Выписки и справки»',
            idCatalog: 'block101&pereydite',
            imageMobile: images.phoneImg1011M,
            imageTablet: images.phoneImg1011,
        },
        {
            id: 1012,
            text: 'Выберите пункт «Справка для госслужащих»',
            idCatalog: 'block101&vyberite',
            imageMobile: null,
            imageTablet: images.phoneImg1012,
        },
        {
            id: 1013,
            text: 'Сохраняйте справки на мобильное устройство или отправляйте на e-mail',
            idCatalog: 'block101&sokhranyayte',
            imageMobile: null,
            imageTablet: images.phoneImg1013,
        },
    ],
}

export const contentBlocks = [
    {
        id: 'plitezhi_i_perevodi',
        moreLink: '#block7',
        items: [
            {
                id: 111,
                title: 'Оплачивайте услуги',
                description: 'Бесплатные платежи по QR-кодам. Оплачивайте сотовую связь, интернет, услуги ЖКХ и другое',
                idCatalog: 'oplachivaite_uslugi',
                imageMobile: null,
                imageTablet: images.phoneImg11,
            },
            {
                id: 112,
                title: 'Управляйте платежами',
                description: 'Создавайте шаблоны или настройте автоплатежи',
                idCatalog: 'upravlyaite_platezhami',
                imageMobile: null,
                imageTablet: images.phoneImg12,
            },
            {
                id: 113,
                title: 'Переводите средства любым удобным способом',
                description: 'Бесплатно по номеру телефона по Системе быстрых платежей, с карты на карты любых банков',
                idCatalog: 'perevodite_sredstva',
                imageMobile: null,
                imageTablet: images.phoneImg13,
            },
            {
                id: 114,
                title: 'Контролируйте расходы',
                description: 'Наглядно отслеживайте историю платежей и переводов в выписке',
                idCatalog: 'controliruite_rashodi',
                imageMobile: images.phoneImg14M,
                imageTablet: images.phoneImg14,
            },
            {
                id: 115,
                title: 'Пополняйте карты с карт других банков',
                description: 'Добавьте карты других банков в приложение в 2 клика',
                idCatalog: 'popolnyaite_karti',
                imageMobile: null,
                imageTablet: images.phoneImg15,
            },
        ],
    },
    {
        id: 'kredit',
        moreLink: '#block3',
        items: [
            {
                id: 111,
                title: 'Оформите кредит онлайн не выходя из дома',
                description: 'Оставьте заявку в мобильном приложении и получите кредит с зачислением на  карту',
                idCatalog: 'oformite_kredit',
                imageMobile: null,
                imageTablet: images.phoneImg21,
            },
            {
                id: 112,
                title: 'Оплачивайте страхование по кредитам',
                description: 'Оформляется по вашему желанию и снижает ставку по кредиту',
                idCatalog: 'oplachivaite_strahovanie',
                imageMobile: null,
                imageTablet: images.phoneImg22,
            },
            {
                id: 113,
                title: 'Совершайте платежи по кредитам',
                description: 'Отслеживайте график платежей и вносите ежемесячные платежи онлайн',
                idCatalog: 'sovershaite_platezhi',
                imageMobile: null,
                imageTablet: images.phoneImg23,
            },
            {
                id: 114,
                title: 'Досрочно погашайте кредит',
                description: 'Частично или полностью',
                idCatalog: 'dosrochno_pogashaite',
                imageMobile: null,
                imageTablet: images.phoneImg24,
            },
        ],
    },
    {
        id: 'kk',
        moreLink: '#block4',
        items: [
            {
                id: 111,
                title: 'Оформите кредитную карту онлайн',
                description: 'Оставьте заявку в мобильном приложении и получите средства на счет. При выборе цифрового типа карты вы сможете пользоваться ей сразу!',
                idCatalog: 'oformite_kred_kartu',
                imageMobile: images.phoneImg31M,
                imageTablet: images.phoneImg31,
            },
            {
                id: 112,
                title: 'Просматривайте детали',
                description: null,
                idCatalog: 'detali',
                imageMobile: images.phoneImg32M,
                imageTablet: images.phoneImg32,
            },
            {
                id: 113,
                title: 'Отслеживайте льготный период',
                description: 'И не платите % до 120 дней',
                idCatalog: 'otslezhivaite_lp',
                imageMobile: images.phoneImg33M,
                imageTablet: images.phoneImg33,
            },
            {
                id: 114,
                title: 'Отслеживайте информацию по выплаченному и начисленному кэшбэку',
                description: null,
                idCatalog: 'otslezhivaite_kb',
                imageMobile: images.phoneImg34M,
                imageTablet: images.phoneImg34,
            },
            {
                id: 115,
                title: 'Вносите платежи',
                description: 'В мобильном приложении указываются срок и сумма минимальных платежей',
                idCatalog: 'vnosite_platezhi',
                imageMobile: null,
                imageTablet: images.phoneImg35,
            },
        ],
    },
    {
        id: 'debet_karti',
        moreLink: '#block5',
        items: [
            {
                id: 111,
                title: 'Оформите карту онлайн не выходя из дома',
                description: 'Оставьте заявку в приложении. Карта виртуальная и не требует посещения офиса! Для получения пластиковой карты выберите город и офис',
                idCatalog: 'oformite_kartu',
                imageMobile: images.phoneImg41M,
                imageTablet: images.phoneImg41,
            },
            {
                id: 112,
                title: 'Оплачивайте покупки сразу после оформления карты',
                description: 'Совершайте бесконтактную оплату или в сети Интернет',
                idCatalog: 'oplachivaite_srazu',
                imageMobile: images.phoneImg42M,
                imageTablet: images.phoneImg42,
            },
            {
                id: 113,
                title: 'Управляйте кэшбэком',
                description: 'Выбирайте рубрики повышенного кэшбэка по карте «ПОРА» хоть каждый месяц',
                idCatalog: 'upravlyaite_kb',
                imageMobile: null,
                imageTablet: images.phoneImg43,
            },
            {
                id: 114,
                title: 'Управляйте картой',
                description: 'Управляйте лимитами, меняйте ПИН-код, настраивайте уведомления, смотрите реквизиты',
                idCatalog: 'upravlyaite_kartoi',
                imageMobile: null,
                imageTablet: images.phoneImg45,
            },
            {
                id: 115,
                title: 'Ознакомьтесь с подробной информацией по кэшбэку',
                description: 'и дополнительными преимуществами по вашей карте',
                idCatalog: 'moi_privilegii',
                imageMobile: images.phoneImg46M,
                imageTablet: images.phoneImg46,
            },
        ],
    },
    {
        id: 'vkladi',
        moreLink: '#block6',
        items: [
            {
                id: 111,
                title: 'Открывайте вклады и накопительные счета онлайн',
                description: 'С привилегиями и повышенными ставками в мобильном приложении',
                idCatalog: 'otkrivaite_vkladi_i_ns',
                imageMobile: images.phoneImg51M,
                imageTablet: images.phoneImg51,
            },
            {
                id: 112,
                title: 'Управляйте вкладами и накопительными счетами онлайн',
                description: 'Пополняйте и снимайте средства в 2 клика',
                idCatalog: 'upravlyaite_vkladami',
                imageMobile: null,
                imageTablet: images.phoneImg52,
            },
            {
                id: 113,
                title: 'Отслеживайте график начисления процентов',
                description: 'Все суммы и даты будущих поступлений будут представлены в таблице',
                idCatalog: 'otslezhivaite_grafik',
                imageMobile: null,
                imageTablet: images.phoneImg53,
            },
            {
                id: 114,
                title: 'Инвестируйте',
                description: 'Выберите стратегию доверительного управления и получайте доход выше ставок по вкладам и уровня инфляции',
                idCatalog: 'investiruite',
                imageMobile: images.phoneImg54M,
                imageTablet: images.phoneImg54,
            },
            {
                id: 115,
                title: 'Переоформляйте вклады и накопительные счета',
                description: 'Для открытия нового вклада переведите средства со вклада до востребования на любой счет и откройте новый вклад',
                idCatalog: 'pereoformlyaite_vkladi',
                imageMobile: null,
                imageTablet: images.phoneImg55,
            },
        ],
    },
    {
        id: 'svyaz',
        moreLink: '#block8',
        items: [
            {
                id: 111,
                title: 'Получайте уведомления о новых возможностях мобильного банка, акциях и предложениях',
                description: null,
                idCatalog: 'uvedomleniya_ikonka',
                imageMobile: null,
                imageTablet: images.phoneImg61,
            },
            {
                id: 112,
                title: 'Обращайтесь в чат мобильного приложения',
                description: 'Мы на связи 24/7',
                idCatalog: 'obrashaites_v_chat',
                imageMobile: null,
                imageTablet: images.phoneImg62,
            },
            {
                id: 113,
                title: 'Смотрите адреса отделений и банкоматов',
                description: 'А так же режим их работы',
                idCatalog: 'smotrite_adresa',
                imageMobile: images.phoneImg63M,
                imageTablet: images.phoneImg63,
            },
            {
                id: 114,
                title: 'Бесплатно звоните в банк',
                description: 'Прямо из приложения',
                idCatalog: 'svyaz&zvonite_v_bank',
                imageMobile: images.phoneImg64M,
                imageTablet: images.phoneImg64,
            },
            {
                id: 115,
                title: 'Настройте уведомления',
                description: 'Выберите push или SMS уведомления для информирования обо всех операциях по вашим счетам.',
                idCatalog: 'nastroite_uvedomleniya',
                imageMobile: null,
                imageTablet: images.phoneImg55,
            },
            {
                id: 116,
                title: 'Входите по номеру карты',
                description: null,
                idCatalog: 'vhodite_po_nomeru_karti',
                imageMobile: null,
                imageTablet: images.phoneImg66,
            },
            {
                id: 117,
                title: 'Восстановите доступ в мобильное приложение, если забыли пароль',
                description: 'по ID, логину или номеру карты',
                idCatalog: 'vosstanovite_dostup',
                imageMobile: null,
                imageTablet: images.phoneImg67,
            },
        ],
    },
    {
        id: 'demo',
        moreLink: '#block1',
        items: [
            {
                id: 111,
                title: 'Попробуйте демо-версию мобильного банка',
                description: 'Нажмите кнопку «Демо-версия» и познакомьтесь с продуктами и услугами мобильного банка УБРиР',
                idCatalog: 'poprobuite_demo',
                imageMobile: null,
                imageTablet: images.phoneImg71,
            },
            {
                id: 112,
                title: 'Все продукты отображаются в демо-режиме',
                description: 'Ознакомьтесь с продуктами и функционалом мобильного банка в демо-режиме',
                idCatalog: 'vse_produkti',
                imageMobile: images.phoneImg72M,
                imageTablet: images.phoneImg72,
            },
            {
                id: 113,
                title: 'Чат с банком',
                description: 'Переходите на вкладку «Чат», где можно получить ответ на  интересующий вопрос онлайн',
                idCatalog: 'chat',
                imageMobile: images.phoneImg73M,
                imageTablet: images.phoneImg73,
            },
        ],
    },
    {
        id: 'personalnie_dannie',
        moreLink: '#block8',
        items: [
            {
                id: 111,
                title: 'Кодовое слово',
                description: 'Чтобы поменять кодовое слово в разделе «Еще» выберите «Персональные данные»',
                idCatalog: 'ks',
                imageMobile: images.phoneImg81M,
                imageTablet: images.phoneImg81,
            },
            {
                id: 112,
                title: 'Изменение кодового слова',
                description: 'Затем выберите «Кодовое слово» и нажмите «Изменить кодовое слово»',
                idCatalog: 'izmenenie_ks',
                imageMobile: images.phoneImg82M,
                imageTablet: images.phoneImg82,
            },
            {
                id: 113,
                title: 'Сохранение изменений',
                description: 'Нажмите «Сохранить», чтобы сохранить внесенные изменения',
                idCatalog: 'sohranenie',
                imageMobile: images.phoneImg83M,
                imageTablet: images.phoneImg83,
            },
            {
                id: 114,
                title: 'Подтверждение смены кодового слова',
                description: 'Подтвердите кодовое слово SMS-кодом',
                idCatalog: 'podtverzhdenie',
                imageMobile: images.phoneImg84M,
                imageTablet: images.phoneImg84,
            },
            {
                id: 115,
                title: 'Готово!',
                description: 'Кодовое слово изменено',
                idCatalog: 'done',
                imageMobile: images.phoneImg85M,
                imageTablet: images.phoneImg85,
            },
        ],
    },
    {
        id: 'dokumenti',
        moreLink: '#block8',
        items: [
            {
                id: 111,
                title: 'Просматривайте и управляйте своими документами',
                description: 'В разделе «Еще» в блоке «Документы банковского обслуживания» всегда есть возможность просмотреть ваши документы',
                idCatalog: 'prosmatrivaite_i_upravlyaite',
                imageMobile: images.phoneImg91M,
                imageTablet: images.phoneImg91,
            },
            {
                id: 112,
                title: 'Сохраняйте и пересылайте документы',
                description: 'Просмотрите документы, при необходимости нажмите «Сохранить или переслать»',
                idCatalog: 'sohranyaite_i_peresilaite',
                imageMobile: images.phoneImg92M,
                imageTablet: images.phoneImg92,
            },
        ],
    },
    {
        id: 'overdraft',
        moreLink: '#block9',
        items: [
            {
                id: 111,
                title: 'Оформите овердрафт онлайн',
                description: 'Оставьте заявку в мобильном приложении и получите средства на счет',
                idCatalog: 'oformite_overdraft',
                imageMobile: null,
                imageTablet: images.phoneImg101,
            },
            {
                id: 112,
                title: 'Просматривайте детали',
                description: 'На экране счета, подключенного к овердрафту, нажмите на «Детали овердрафта»',
                idCatalog: 'prosmatrivaite_detali',
                imageMobile: images.phoneImg102M,
                imageTablet: images.phoneImg102,
            },
            {
                id: 113,
                title: 'Отслеживайте сроки оплаты',
                description: 'Посмотреть сроки оплаты и долг по овердрафту можно на странице счета',
                idCatalog: 'otslezvivaite_sroki',
                imageMobile: images.phoneImg103M,
                imageTablet: images.phoneImg103,
            },
            {
                id: 114,
                title: 'Вносите платежи',
                description: 'В мобильном приложении указываются срок и сумма минимальных платежей',
                idCatalog: 'vnosite_platezhi',
                imageMobile: images.phoneImg104M,
                imageTablet: images.phoneImg104,
            },
            {
                id: 115,
                title: 'Закрытие овердрафта',
                description: 'При необходимости отключить овердрафт так же легко как подключить',
                idCatalog: 'zakritie_overdrafta',
                imageMobile: images.phoneImg105M,
                imageTablet: images.phoneImg105,
            },
        ],
    },
]